language: java

services:
  - docker

script:
  - docker pull confluentinc/ksqldb-cli:0.24.0
  - docker build -t abraham-leal/ksql-pipeline .
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "main" ]; then /bin/bash -c "docker run abraham-leal/ksql-pipeline /bin/bash -c "cd /build; ksql-migrations apply -c execution/ksql-migrations.properties -a""; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then /bin/bash -c "docker run abraham-leal/ksql-pipeline /bin/bash -c "/build/testing/run_ksql_tests.sh""; fi'