language: java

services:
  - docker

script:
  - docker pull confluentinc/ksqldb-cli:0.24.0
  - docker build -t abraham-leal/ksql-pipeline .
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash docker run abraham-leal/ksql-pipeline /bin/bash -c "ksql-migrations apply -a -c execution/ksql-migrations.properties"; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash docker run abraham-leal/ksql-pipeline /bin/bash -c "/build/testing/run_ksql_tests.sh"; fi'